export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USERS_MODEL = 'USERS_MODEL';
export const LOG_IN_ATTEMPTS_MODEL = 'LOG_IN_ATTEMPTS_MODEL';
export const OLD_REFRESH_TOKENS_MODEL = 'OLD_REFRESH_TOKENS_MODEL';
export const TWO_F_AUTH_REQS_MODEL = 'TWO_F_AUTH_REQS_MODEL';